site_name: prostata
site_description: A Python library for PROcessing STATistics with timers, counters, ratios, and attributes
site_author: merlos
site_url: https://merlos.github.io/prostata/

repo_name: merlos/prostata
repo_url: https://github.com/merlos/prostata
edit_uri: edit/main/docs/

plugins:
  - mike:
      # https://pypi.org/project/mike/
      alias_type: symlink
      redirect_template: null
      deploy_prefix: ''
      canonical_version: 'latest'
      version_selector: true
      css_dir: css
      javascript_dir: js



theme:
  name: material
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  features:
    - content.code.copy
    - content.code.annotate
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.suggest
    - search.highlight
    - toc.follow

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
            show_root_heading: true
            show_source: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true

nav:
  - Home: index.md
  - User Guide:
      - Getting Started: user-guide/getting-started.md
      - Timers: user-guide/timers.md
      - Counters: user-guide/counters.md
      - Ratios: user-guide/ratios.md
      - Attributes: user-guide/attributes.md
      - Labels: user-guide/labels.md
      - Dynamic Methods: user-guide/dynamic-methods.md
  - API Reference:
      - Stats: api/stats.md
  - Development:
      - Contributing: development/contributing.md
      - Testing: development/testing.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/merlos/prostata
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/prostata/

  version:
    provider: mike

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - admonition
  - attr_list
  - md_in_html
  - tables
  - toc:
      permalink: true